[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
true_news = "72p69CwNBNFkgT1NE8UfHqqMDDinn4sQjQcGa3yfEt5Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sanjeet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
