[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
true_news = "nyzossX1y8qY1BusJur1ckHfLzrtRxwpgvwpBuvJBMc"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "localnet"
wallet = "/home/sanjeet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
