export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

/*
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
 */

import "@/app/ui/global.css";
import { inter } from "@/app/ui/fonts";
//import SolWalletProvider from "./ui/solWalletProvider";
import SolWalletProvider from "../ui/solWalletProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <SolWalletProvider />
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
